services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80" # Porta para acessar o Nginx
      - "443:443"
    depends_on:
      - coraza

  coraza:
    build:
      context: ./coraza-waf
    volumes:
      - ./logs:/tmp # Monta o diretório de logs
      - ./coraza-waf:/coraza-waf # Inclui as configurações do Coraza
   
    depends_on:
      - app

  app:
    build:
      context: ./app
    